version: '2'
networks:
  application_network:
services:
  mywebapp:
    restart: "always"
    image: mywebapp
    container_name: "mywebapp"
    environment:
      PORT: 80
      VIRTUAL_HOST: www.yourdomain.com
      LETSENCRYPT_HOST: www.yourdomain.com
      LETSENCRYPT_EMAIL: your-address@email.com
    networks: 
      - application_network
